services:
  postgres:
    image: postgres:16.1-alpine
    container_name: bank-postgres-db
    env_file:
      - .env
    ports:
      - "${POSTGRESQL_EXT_PORT}:${POSTGRESQL_PORT}"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} && psql -U ${POSTGRES_USER} -d ${POSTGRES_DB} -c 'SELECT 1'" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - bank-postgres-db-data:/var/lib/postgresql/data
volumes:
  bank-postgres-db-data: